# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ICON-tracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICON-tracker
  pod 'ICONKit', '~> 0.3.0'
  pod 'BigInt'
  pod 'ReactorKit'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'Alamofire', '~> 5.0.0-beta.3'

end
